# Generated by Django 5.0.6 on 2024-06-04 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nomProducto', models.CharField(max_length=30, verbose_name='Producto')),
                ('descProducto', models.CharField(max_length=550, verbose_name='Descripción')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90000)], verbose_name='Precio')),
            ],
        ),
    ]
