# Generated by Django 5.0.6 on 2024-06-18 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('idCurso', models.IntegerField(primary_key=True, serialize=False, verbose_name='idCursos')),
                ('nomCurso', models.CharField(max_length=50, verbose_name='nomCursos')),
                ('descCurso', models.CharField(max_length=300, verbose_name='descCurso')),
                ('precioCurso', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)], verbose_name='Precio')),
                ('duracion', models.CharField(max_length=15, verbose_name='duracion')),
                ('cupos', models.IntegerField(verbose_name='cupos')),
                ('horario', models.CharField(choices=[('mt', 'Mañana 08:00 - 12:00 / Tarde 17:00 - 21:00'), ('ma', 'Mañana 08:00 - 12:00'), ('ta', 'Tarde 17:00 - 21:00')], default='mt', max_length=2)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('img', models.ImageField(null=True, upload_to='imagenes', verbose_name='img')),
            ],
        ),
    ]
