# Generated by Django 5.0.6 on 2024-06-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fechaTermino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
