# Generated by Django 5.0.6 on 2024-06-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boleta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('RE', 'Recibido'), ('NR', 'No Recibido'), ('PP', 'Procesando Pedido')], default='RE', max_length=2),
        ),
    ]
